# GitHub Labels Configuration
# This file defines all labels used in the repository for automated workflows

# Priority Labels
- name: "priority/critical"
  color: "d73a4a"
  description: "Critical priority - needs immediate attention"

- name: "priority/high"
  color: "ff6b6b"
  description: "High priority - should be addressed soon"

- name: "priority/medium"
  color: "fbca04"
  description: "Medium priority - normal queue"

- name: "priority/low"
  color: "0e8a16"
  description: "Low priority - can be addressed later"

# Type Labels
- name: "type/bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "type/feature"
  color: "a2eeef"
  description: "New feature or request"

- name: "type/enhancement"
  color: "84b6eb"
  description: "Improvement to existing feature"

- name: "type/documentation"
  color: "0075ca"
  description: "Documentation improvements"

- name: "type/refactor"
  color: "d4c5f9"
  description: "Code refactoring"

- name: "type/performance"
  color: "ff9500"
  description: "Performance improvements"

- name: "type/security"
  color: "b60205"
  description: "Security-related changes"

# Size Labels (auto-generated by PR automation)
- name: "size/XS"
  color: "3cbf00"
  description: "Extra small changes (< 10 lines)"

- name: "size/S"
  color: "5d9cec"
  description: "Small changes (10-100 lines)"

- name: "size/M"
  color: "007ec6"
  description: "Medium changes (100-500 lines)"

- name: "size/L"
  color: "f9d71c"
  description: "Large changes (500-1000 lines)"

- name: "size/XL"
  color: "ee0701"
  description: "Extra large changes (> 1000 lines)"

# Component Labels
- name: "components"
  color: "1d76db"
  description: "Changes to React components"

- name: "hooks"
  color: "0052cc"
  description: "Changes to React hooks"

- name: "styles"
  color: "e99695"
  description: "Styling and CSS changes"

- name: "types"
  color: "5319e7"
  description: "TypeScript type definitions"

- name: "tests"
  color: "0e8a16"
  description: "Test-related changes"

- name: "demo"
  color: "fbca04"
  description: "Demo application changes"

- name: "build"
  color: "d4c5f9"
  description: "Build system changes"

# Workflow Labels
- name: "dependencies"
  color: "0366d6"
  description: "Dependency updates"

- name: "ci/cd"
  color: "28a745"
  description: "CI/CD pipeline changes"

- name: "security"
  color: "b60205"
  description: "Security-related changes"

- name: "automated"
  color: "ededed"
  description: "Automated changes (bots, scripts)"

# Status Labels
- name: "status/needs-review"
  color: "fbca04"
  description: "Needs code review"

- name: "status/needs-testing"
  color: "d4c5f9"
  description: "Needs testing"

- name: "status/blocked"
  color: "d73a4a"
  description: "Blocked by other work"

- name: "status/work-in-progress"
  color: "ff9500"
  description: "Work in progress"

- name: "status/ready-to-merge"
  color: "0e8a16"
  description: "Ready to merge"

# Release Labels
- name: "release/patch"
  color: "c2e0c6"
  description: "Patch release (bug fixes)"

- name: "release/minor"
  color: "bfd4f2"
  description: "Minor release (new features)"

- name: "release/major"
  color: "f9d71c"
  description: "Major release (breaking changes)"

- name: "release/prerelease"
  color: "d4c5f9"
  description: "Pre-release version"

# Special Labels
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

# Breaking Changes
- name: "breaking-change"
  color: "d73a4a"
  description: "Contains breaking changes"

# Platform Labels
- name: "platform/web"
  color: "0052cc"
  description: "Web platform specific"

- name: "platform/mobile"
  color: "1d76db"
  description: "Mobile platform specific"

- name: "browser/chrome"
  color: "4285f4"
  description: "Chrome browser specific"

- name: "browser/firefox"
  color: "ff9500"
  description: "Firefox browser specific"

- name: "browser/safari"
  color: "0070c9"
  description: "Safari browser specific"

- name: "browser/edge"
  color: "0078d4"
  description: "Edge browser specific" 