image: 'restyled/restyler-prettier:v3.0.3-2'
command:
  - prettier
  - '--write'
arguments: []
include:
  - '**/*.js'
  - '**/*.ts'
  - '**/*.jsx'
  - '**/*.tsx'
interpreters: []
exclude:
  - "**/*.patch"
  - "**/node_modules/**/*"
  - "**/vendor/**/*"
  - ".github/workflows/**/*"
  - ".gitignore"
  - "pnpm-lock.yaml"
  - "**/tsconfig.json"
  - coverage/**
